### ISSUE TITLE
项目是asp.net mvc 服务端，应该怎么搭呀

### ISSUE THREAD

**Issue by MaQuanXin** [lishewen/WeChatMiniAppSignalRClient#4]
项目是asp.net mvc 服务端和asp.net core 不一样，菜鸟一枚，求指教

**Comment by lishewen** [comment]
那就换asp.net core呗，传统asp.net对websocket wss的支持又不好，对服务器要求又高，要win2012+iis8.0以上才有websocket支持，.net core去阿里云、腾讯云找台1核1G的Linux学生机，随便玩

**Comment by MaQuanXin** [comment]
换asp.net core 的话得把原有的mvc 上webapi 也搬过去，不知道可行不可行

**Comment by lishewen** [comment]
我都把我自己以前的MVC项目全改core了，也帮不少公司改过（收费）
